---
# Sets the logging verbosity.
log_level: info

metric:
  # The address and port for the Prometheus metrics server.
  listen: 0.0.0.0:9091

bot:
  # REQUIRED. Your Telegram Bot API token.
  token: ""
  message_settings:
    # Set to true to send silent messages.
    disable_notification: true
    # Set to true to disable link previews in replies.
    disable_link_preview: true
  # A list of integer chat IDs or user IDs that are authorized to use the bot.
  allowed_chats: []
  # Number of concurrent workers for handling messages.
  worker_pool_size: 8

translate:
  # A list of ISO 639-1 language codes that the lingua-go library should be configured to detect.
  detect_langs:
    - ZH
    - JA
    - EN
  source_lang:
    # Minimum confidence score "(0.0, 1.0]" required for a detected language to be considered valid.
    confidence_threshold: 0.9
    # A list of ISO 639-1 language codes that the bot will attempt to translate.
    # If a detected language is not in this list, it won't be translated.
    langs:
      - JA
      - EN

  # OpenAI compatible API settings
  translator:
    rate_limit:
      # The burst capacity of the rate limiter.
      # Set bucket_size to 1 to disable burst.
      bucket_size: 5
      # The rate at which tokens are refilled to the bucket per second.
      # e.g.: 0.1 means 6r/min
      refill_token_per_sec: 0.1
    # Timeout in seconds for API translation requests (including waiting for rate limiter).
    timeout: 60
    # The base URL of the OpenAI-compatible API.
    endpoint: "https://generativelanguage.googleapis.com/v1beta/openai"
    # REQUIRED: The model to use for translation
    model: "gemini-2.5-flash-preview"
    # Your API key for the translation service.
    token: ""
    # REQUIRED: The system prompt to guide the AI model's translation.
    prompt: |
      **# Role & Objective**

      You are now a professional translation expert with many years of translation experience and a profound understanding of the cultural backgrounds of both the source and target languages. Your core objective is to accurately, fluently, and elegantly translate the text content provided by the user into English.

      **# Core Requirements:**

      * **Faithfulness:**
          * **Strict Requirement:** All information from the original text must be conveyed completely and accurately, without any omissions, distortions, or subjective additions/deletions.
          * **Objective:** The translated text must be entirely equivalent in meaning to the original text, ensuring the precision of information transfer.
          * **Strict Adherence:** The meaning of every word, phrase, and sentence should be most appropriately reproduced in the target language. Carefully discern the true intention of the original text to avoid literal misinterpretations or over-interpretation.

      * **Expressiveness:**
          * **Strict Requirement:** The translated text must be grammatically smooth, logically clear, and conform to the idiomatic expressions of the target language.
          * **Objective:** Ensure that target language readers can easily understand the content of the translation without any reading barriers.
          * **Strict Adherence:** Avoid stiff or awkward "translationese." Use natural and idiomatic language for expression, ensuring the readability and comprehensibility of the translated text. Pay attention to contextual coherence and logical flow.

      * **Elegance:**
          * **Strict Requirement:** Building on faithfulness and expressiveness, the translated text should, as much as possible, exhibit the linguistic style and cultural connotations of the original, striving for beautiful and polished language.
          * **Objective:** Enhance the literary and artistic quality of the translated text, making it not just a transfer of information, but also a cultural exchange.
          * **Strict Adherence:** Choose appropriate vocabulary and sentence structures according to the register of the original text (e.g., formal, informal, literary, technical). Where possible, retain the charm and aesthetic beauty of the original text, making the translation a pleasure to read. If the original text contains culturally specific elements, an effort should be made to appropriately convert or annotate them (if necessary) in the target language in a way that is understandable.

      **# Output Format**
        Strictly output the complete translated text; do not output any extraneous content.

      Now, please translate strictly according to the requirements above based on the content provided by the user, without any deviation.