---
# Sets the logging verbosity.
log_level: info

metric:
  # The address and port for the Prometheus metrics server.
  listen: 0.0.0.0:9091

bot:
  debug: false
  # REQUIRED. Your Telegram Bot API token.
  token: ""
  message_settings:
    # Set to true to send silent messages.
    disable_notification: true
    # Set to true to disable link previews in replies.
    disable_link_preview: true
  # A list of integer chat IDs or user IDs that are authorized to use the bot.
  allowed_chats: []
  # Number of concurrent workers for handling messages.
  worker_pool_size: 8

translate_service:
  max_retry: 3
  retry_cooldown: 30

  # Configuration for language detectors
  # Can be "fallback" or "wrr" (Weighted Round Robin)
  language_detector_selector: fallback
  language_detectors:
    - name: "lingua_default"
      # Specifies the type of detector
      type: "lingua"
      # Used if language_detector_selector is "wrr"
      weight: 1
      # Configuration specific to the 'lingua' type
      lingua:
        # A list of ISO 639-1 language codes that this lingua-go instance should be configured to detect.
        detect_langs:
          - ZH
          - JA
          - EN
        # Minimum confidence score (0.0, 1.0] required for a detected language to be considered valid by this detector.
        source_lang_confidence_threshold: 0.9
        # A list of ISO 639-1 language codes that this detector will report as valid.
        source_lang_filter: ["JA", "EN"]

  # default settings
  default_translator_config:
    # failover settings
    #  this config will disable translators consistely fail for:
    #  1  failure:  no cooldown
    #  2  failures: no cooldown
    #  3  failures: 1 * 120 secs cooldown
    #  6  failures: 2 * 120 secs cooldown
    #  9  failures: 3 * 120 secs cooldown
    #  12 failures: 4 * 120 secs cooldown
    #  15 failures: 5 * 120 secs cooldown
    #  18 failures: disable it until next config reloading or restarting
    failover:
      max_failures: 3
      cooldown_base_sec: 120
      max_disable_cycles: 6
    weight: 1
    # REQUIRED: The system prompt to guide the AI model's translation.
    system_prompt: |
      You are now an extremely demanding, almost perversely so, expert specializing in translating other languages into English.

      During your translation process, the requirements are as follows:
      - You must strictly base your translation on the original text. The translated text must be completely equivalent in meaning to the original, ensuring the accuracy of information transmission.
      - The meaning of every word, phrase, and sentence should be most appropriately reproduced in the target language. Carefully discern the true intention of the original text, avoiding literal translation without understanding or over-interpretation.
      - While strictly adhering to the original text, the translation must be fluent, logically clear, and conform to the idiomatic expressions of the target language.
      - While strictly adhering to the original text and maintaining logical fluency, the translation should, as much as possible, exhibit the linguistic style and cultural connotations of the original text, striving for elegant and refined language.
      - You must firmly remember that your task is translation, not answering questions or expanding on the text. You must strictly execute the translation task.

      Output format: Strictly output the complete translated text. Do not output any superfluous content or omit any content.

      Now, please strictly follow the requirements above to translate the content provided by the user, without any deviation.

  translator_selector: fallback
  translators:
    - name: translator-01
      type: openai
      # Timeout in seconds for API translation requests.
      timeout: 60
      # The base URL of the OpenAI-compatible API.
      endpoint: "https://generativelanguage.googleapis.com/v1beta/openai"
      # REQUIRED: The model to use for translation
      model: "gemini-2.5-flash-preview"
      # Your API key for the translation service.
      token: ""
      rate_limit:
        enabled: true
        # The burst capacity of the rate limiter.
        # Set bucket_size to 1 to disable burst.
        bucket_size: 5
        # The rate at which tokens are refilled to the bucket per second.
        # e.g.: 0.1 means 6r/min
        refill_token_per_sec: 0.1
    